In [60]:
## import libraries
import pandas as pd
from sklearn import linear_model
from word2number import w2n
import numpy as np
from sklearn import preprocessing

In [36]:
## import the dataset
df = pd.read_csv("hiring.csv")

In [37]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [38]:
temp = df["experience"].isna().value_counts()

In [39]:
## fill experience nan
df["experience"] = df["experience"].fillna("zero")

In [40]:
def to_num(str):
    return(w2n.word_to_num(str))

In [41]:
## change words to numbers
df["experience"] = df["experience"].apply(to_num) 

In [42]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [43]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].median())

In [44]:
temp[1]

2

In [45]:
## function to find out no. of nan values:

def find_nan(df):
    for col in df.columns:
        try:
            print("For columns : ",col)
            temp_series = df[col].isna().value_counts()
            print(col," has",temp_series[1],"missing values")
        except:
            print(col," has no missing values")

In [46]:
find_nan(df)

For columns :  experience
experience  has no missing values
For columns :  test_score(out of 10)
test_score(out of 10)  has no missing values
For columns :  interview_score(out of 10)
interview_score(out of 10)  has no missing values
For columns :  salary($)
salary($)  has no missing values


In [13]:
df.describe()

experience  test_score(out of 10)  interview_score(out of 10)  \
count     8.00000               8.000000                    8.000000   
mean      4.75000               7.875000                    7.875000   
std       4.26782               1.246423                    1.642081   
min       0.00000               6.000000                    6.000000   
25%       1.50000               7.000000                    6.750000   
50%       4.00000               8.000000                    7.500000   
75%       7.75000               8.250000                    9.250000   
max      11.00000              10.000000                   10.000000   

         salary($)  
count      8.00000  
mean   63000.00000  
std    11501.55269  
min    45000.00000  
25%    57500.00000  
50%    63500.00000  
75%    70500.00000  
max    80000.00000

In [48]:
df["test_2"] = df["test_score(out of 10)"]

In [49]:
## regression
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),df["salary($)"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [50]:
reg.coef_

array([2812.95487627,  922.85298399, 2205.24017467,  922.85298399])

In [15]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [51]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)', 'test_2'],
      dtype='object')

In [24]:
reg.predict(np.array([[1,2,3],[2,3,4]]))

array([30857.35080058, 37721.25181951])

In [25]:
x = np.array([[1,2,3],[2,3,4]])

In [28]:
df_t = pd.DataFrame(x,columns = ["a","b","c"])

In [29]:
df_t

a  b  c
0  1  2  3
1  2  3  4

In [30]:
import pickle

In [31]:
with open("pickle_linear","wb") as f:
    pickle.dump(reg,f)

In [34]:
with open("pickle_linear","rb") as f:
    reg2 = pickle.load(f)

In [35]:
reg2.predict(np.array([[1,2,3],[2,3,4]]))

array([30857.35080058, 37721.25181951])

In [53]:
df = pd.read_csv("hiring.csv")

In [61]:
le = preprocessing.LabelEncoder()

In [64]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [63]:
df["experience"] = df["experience"].fillna("zero")

In [65]:
le.fit(df.experience)

LabelEncoder()

In [67]:
list(le.classes_)

['eleven', 'five', 'seven', 'ten', 'three', 'two', 'zero']

In [68]:
#NOTE encoding EXPERIENCE IS NOT ADVISED BECAUSE WE WANT TO PRESERVE THE NUMERICAL PROPERTY OF THE EXPERIENCE
le.transform(df.experience)

array([6, 6, 1, 5, 2, 4, 3, 0], dtype=int64)

In [69]:
df.experience = le.transform(df.experience)

In [70]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           1                    6.0                           7      60000
3           5                   10.0                          10      65000
4           2                    9.0                           6      70000
5           4                    7.0                          10      62000
6           3                    NaN                           7      72000
7           0                    7.0                           8      80000